/*
Timestamp: 6 March 2026 01:20
File: app/analytics/PredictiveMaintenanceAlerts.tsx

Purpose
-------
Displays predictive maintenance alerts
generated by the intelligence engine.
*/

"use client"

import { useEffect, useState } from "react"

type Alert = {
  vin:string
  component:string
  predicted_risk:number
  severity:string
}

export default function PredictiveMaintenanceAlerts(){

  const [alerts,setAlerts] = useState<Alert[]>([])

  useEffect(()=>{

    async function load(){

      try{

        const res =
          await fetch("/api/intelligence/predictive-maintenance")

        if(!res.ok) return

        const data = await res.json()

        setAlerts(data)

      }
      catch(err){

        console.error("Maintenance alert load error:",err)

      }

    }

    load()

  },[])

  return(

    <div className="bg-white border rounded-xl p-6 shadow-sm">

      <div className="text-lg font-semibold mb-4">
        Predictive Maintenance Alerts
      </div>

      {alerts.length === 0 && (

        <div className="text-gray-500">
          No predictive alerts detected
        </div>

      )}

      {alerts.map((a,index)=>(

        <div
          key={index}
          className="flex justify-between border-b py-2"
        >

          <div>

            <div className="font-medium">
              {a.vin}
            </div>

            <div className="text-sm text-gray-500">
              {a.component}
            </div>

          </div>

          <div
            className={
              a.severity === "High"
                ? "text-red-600"
                : a.severity === "Medium"
                ? "text-orange-600"
                : "text-blue-600"
            }
          >

            {a.predicted_risk}%

          </div>

        </div>

      ))}

    </div>

  )

}